services:
  redis:
    image: redis:latest
    networks:
      - shortlink
    ports:
      - 6379:6379
  app:
    build:
      context: ../
      dockerfile: ./deploy/Dockerfile
    networks:
      - shortlink
    depends_on:
      - redis
    ports:
      - 3000:3000
    environment:
      REDIS_URL: "redis://redis:6379"

networks:
  shortlink:
    external: false
